import { runAgentInfrastructureTests } from '../tests';
import { runAgentModelTests } from '../model/modelTests';
import { runTrackerTimelineTests, runTrackerRegistryTests } from '../trackers/tests';
import { runConditionTreeTests } from '../trackers/conditionTests';
import { runHistoricalValidationTests } from '../../backtester/historicalTests';
import { runActivityPersistenceTests, runTimelineWriteCoalescingTests } from '../activityTests';
import { runExecutionRiskTests } from '../../execution/tests';
import { runGoatTests } from '../../goat/tests';
import { runDefinitionTests } from '../../goat/definitionTests';

await runAgentInfrastructureTests();
await runAgentModelTests();
runTrackerRegistryTests();
await runTrackerTimelineTests();
runConditionTreeTests();
runHistoricalValidationTests();
await runExecutionRiskTests();
await runActivityPersistenceTests();
await runTimelineWriteCoalescingTests();
await runGoatTests();
await runDefinitionTests();
console.log('Agent infrastructure, tracker and timeline tests passed.');
